### ISSUE TITLE
Don't remove foreign classes' event handlers

### ISSUE THREAD

**Issue by tboeckel** [widelec-BB/KwaKwa#1]
This is the file in question:
https://github.com/widelec-BB/KwaKwa/blob/master/inputfield.c

Why does your code remove the internal eventhandler of TextEditor.mcc while it is active? If you plan to override certain input handling with an event handler and want to prevent other objects (or the superclass of your own object) from handling events that you already handled in a special way, then the best approach is to give your own event handler a high priority (i.e. +10 instead of 0 or +1) and return MUI_EventHandlerRC_Eat for each event you want to prevent to be seen by other classes (or your superclass). In no way whatsoever should the event be passed to the superclass by calling DoSuperMethod(). If the superclass of a class has to do its own special event handling then the super class would have added its own event handler anyway.

Finally your hack makes it necessary to use fixed offsets into the instance data of foreign classes. This will only work as long as the layout of the instance data of TextEditor.mcc do not change. This is something that I cannot promise. It may happen at some time that some variables are no longer required and will be removed and hence the offset of TE.mcc's event handler structure within the instance data will definitely change and this will cause KwaKwa to crash as soon as it tries to remove TE.mcc's event handler. This is really bad style, especially when such a bad crash can be avoided so easily as I explained above.

**Comment by widelec-BB** [comment]
AFAIR I tried installing EventHandler with higher priority, but something wasn't working as I expected to. Unfortunately I don't remember what, it was really long time ago.

Of course this hack will broke if the private data of TextEditor.mcc will be changed (as many others hacks in this source code). It's stated in documentation - only V15.45 is supported.
